# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'



# File: azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: stage1
  jobs: 
  - job: job1
    steps:
    - script: echo stage1
# - template: templates/stages1.yml
- stage: stage2
  jobs:
  - job: job2
    steps:
    - script: echo stage2
# - template: templates/stages2.yml
- stage: stage3
  jobs:
  - job: job3
    steps:
    - script: echo stage3
    
