name: code-scan

# Were we can define the inputs that our action will accept
inputs:
  aa: 
    required: true
  bb:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
  - name: code scan
    shell: bash
    run: |
      echo code scanning 
      echo "${{ inputs.aa }}"
      echo "${{ inputs.bb}}"
