name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build 1
      run: |
        echo hello prj1! build-job~
  build-cli-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build 3
      run: |
        echo hello prj1! build-cli-job~
        mkdir output
        echo "code-coverage-report xxxxx" > output/code-coverage.html
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: output/code-coverage.html
  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job,build-cli-job]
    steps:
    - name: Install and Build 2
      run: |
        echo hello prj1! deploy-job~
