name: "Workflow 2"
on:
  push:
    branches:
      - main
jobs:
  xxx-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Deploy
      # Just need to pass the path from action
      uses: "./.github/actions/code-scan" 
      # Defining the variables required in our action
      with:
        aa: "123"
        bb: "456"
        
  xxx2-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
  
  xxx3-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
