name: "Workflow 2"
on:
  push:
    branches:
      - main
jobs:
  xxx-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Deploy
      # Just need to pass the path from action
      uses: "./.github/template/code-scan" 
      # Defining the variables required in our action
      with:
        aa: "123"
        bb: "456"
